# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(944, 803)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setMinimumSize(QtCore.QSize(0, 0))
        self.label_image.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_openimg = QtWidgets.QPushButton(Form)
        self.pushButton_openimg.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_openimg.setObjectName("pushButton_openimg")
        self.horizontalLayout.addWidget(self.pushButton_openimg)
        self.pushButton_openvideo = QtWidgets.QPushButton(Form)
        self.pushButton_openvideo.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_openvideo.setObjectName("pushButton_openvideo")
        self.horizontalLayout.addWidget(self.pushButton_openvideo)
        self.pushButton_opencam = QtWidgets.QPushButton(Form)
        self.pushButton_opencam.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_opencam.setObjectName("pushButton_opencam")
        self.horizontalLayout.addWidget(self.pushButton_opencam)
        self.pushButton_detect = QtWidgets.QPushButton(Form)
        self.pushButton_detect.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.horizontalLayout.addWidget(self.pushButton_detect)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_image.setText(_translate("Form", "TextLabel"))
        self.pushButton_openimg.setText(_translate("Form", "打开图片"))
        self.pushButton_openvideo.setText(_translate("Form", "打开视频"))
        self.pushButton_opencam.setText(_translate("Form", "打开摄像头"))
        self.pushButton_detect.setText(_translate("Form", "检测"))
